site_name: Note
site_url: https://cicada1208.github.io/Note/
nav:
  - Home: index.md
  - Test: test.md
theme:
  name: material
  features:
    - content.code.copy
validation:
  absolute_links: ignore
  nav:
    omitted_files: ignore
markdown_extensions:
  - toc:
      permalink: 🔗
  - attr_list
