site_name: Note
site_url: https://cicada1208.github.io/Note/
nav:
  - Home: index.md
  - Test: test.md
  - Tags: tags.md
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
markdown_extensions:
  - toc:
      permalink: 🔗
  - attr_list
plugins:
  - search
  - tags
validation:
  absolute_links: ignore
  nav:
    omitted_files: ignore
