site_name: Note
# if setting up site_url, don't use default --dev-addr of mkdocs serve.
# e.g. change localhost:8000 to localhost:8001
site_url: https://cicada1208.github.io/Note
repo_url: https://github.com/cicada1208/Note
repo_name: cicada1208/Note
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - Test: test.md
  - Tags: tags.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cicada1208/Note
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.tooltips
    - content.action.edit
    - content.action.view
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
markdown_extensions:
  - toc:
      permalink: 🔗
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search
  - tags
  - glightbox:
      auto_caption: true
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     type: iso_datetime
validation:
  absolute_links: ignore
  nav:
    omitted_files: ignore
