[build]
  command = "pip install . --user && export PATH=$HOME/.local/bin:$PATH && mkdocs build"
  publish = "site"

[build.environment]
  PYTHON_VERSION = "3.9"

[[headers]]
  for = "/*"
  [headers.values]
    Basic-Auth = "cicada:unicorn1208"