[build]
  command = "pip install . && mkdocs build"
  publish = "site"

[build.environment]
  PYTHON_VERSION = "3.13"

[[headers]]
  for = "/*"
  [headers.values]
    Basic-Auth = "cicada:unicorn1208"