name: gh-cicd
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install MkDocs And StatiCrypt
        run: |
          pip install .
          npm install -g staticrypt
      - name: Build MkDocs Site
        run: mkdocs build
      - name: Encrypt All HTML Files With StatiCrypt
        run: |
          find site -type f -name "*.html" -exec staticrypt {} --password ${{ secrets.STATICRYPT_PASSWORD }} --short \;
          ls -l encrypted/
          cp -rf encrypted/* site
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
      # - name: Deploy Encrypted Site To GitHub Pages
      #   run: |
      #     git add -f site
      #     git commit -m "Deploy encrypted site"
      #     git subtree split --prefix site main -b temp-branch
      #     git push -f origin temp-branch:gh-pages
      #     git branch -D temp-branch
