name: gh-cicd
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install MkDocs and StatiCrypt
        run: |
          pip install .
          npm install -g staticrypt
      - name: Build MkDocs Site
        run: mkdocs build
      - name: Encrypt All HTML Files with StatiCrypt
        run: find site -type f -name "*.html" -exec staticrypt {} --password test --short -o {} \;
      - name: Deploy Encrypted Site to GitHub Pages
        run: |
          git add site
          git commit -m "Deploy encrypted site"
          git push -f origin `git subtree split --prefix site main`:gh-pages
